language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: HwYiEWjP2EgtJIRRjYGHYOK/xjzDH3gEUBqXRs0kaensTWOrYn/vfiHvbYZAVN2E0CFJ9ZHm/Saw0eYjlPDrqglRVeOXbkUqDa3sclioqBQ3xtsu1ZiZ6i3LCILGVWZMft/O+nSo3keFHgLnl7eJiWfOVZLjFWT/6ccD0r7zc9yYVfpM+QIsC5Zt4zG16ti/Ia1V2LynFTlyOZsYgyFsc0s40Y07udwYpWPYJxzQs5MykSZZQWsXMm0AQI/xdN5AV61/6PjGQyd+D5DBwJb0udEjebMVGSAl1EPstdP+8xot5j64faJ3BNy0S9SAK1llRXFUlp8sWlX0xTfvOywFs5FjIoFHvuntFwxYOoX+RibpmETdPZjAtTwlpWG5PirKJT7op/4LBxOLk/rzKWxw0AMbd5oQJ7VqRlZnl/I6/JLSZZXmgyRQZtE7+0ZepXl5AzuXVJN0Qs3iuBTCNoZ+ABorm3rbmDbk4l2N3ycZPw5evKbLxOIIaC3/CTjK5nurIQJlYXlrxi8ra6XpMCjUFgTrIiaMAQNvhjoSCaryY2sfMKscOP9aTuiEQcfMEVYMHyyJQEbBFzI+wzbvykiy4gPSkwrmBJKxA2iNirEFhXYjfQne1KRyONjWMyG4RXMqor966rBnNvyIZurnehnAWJ8RmNY/+co6AqWKh90lejo=
